// flow-typed signature: e6e84aa5fdd7e88a2cf0b6939a941527
// flow-typed version: <<STUB>>/@mdi/font_v^2.5.94/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mdi/font'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mdi/font' {
  declare module.exports: any;
}
