// flow-typed signature: bc41717acf7321d037c4db5da2bb59da
// flow-typed version: <<STUB>>/apollo-link-context_v^1.0.3/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-link-context'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-link-context' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-link-context/lib/bundle.cjs' {
  declare module.exports: any;
}

declare module 'apollo-link-context/lib/bundle.esm' {
  declare module.exports: any;
}

declare module 'apollo-link-context/lib/bundle.umd' {
  declare module.exports: any;
}

declare module 'apollo-link-context/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-link-context/lib/bundle.cjs.js' {
  declare module.exports: $Exports<'apollo-link-context/lib/bundle.cjs'>;
}
declare module 'apollo-link-context/lib/bundle.esm.js' {
  declare module.exports: $Exports<'apollo-link-context/lib/bundle.esm'>;
}
declare module 'apollo-link-context/lib/bundle.umd.js' {
  declare module.exports: $Exports<'apollo-link-context/lib/bundle.umd'>;
}
declare module 'apollo-link-context/lib/index.js' {
  declare module.exports: $Exports<'apollo-link-context/lib/index'>;
}
