// flow-typed signature: 0febe5612a1c3120784a9a1fdd857e56
// flow-typed version: <<STUB>>/dhtmlx-gantt_v^6.1.6/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dhtmlx-gantt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dhtmlx-gantt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dhtmlx-gantt/codebase/dhtmlxgantt' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/ext/dhtmlxgantt_csp' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/ext/dhtmlxgantt_fullscreen' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/ext/dhtmlxgantt_keyboard_navigation' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/ext/dhtmlxgantt_marker' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/ext/dhtmlxgantt_multiselect' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/ext/dhtmlxgantt_quick_info' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/ext/dhtmlxgantt_smart_rendering' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/ext/dhtmlxgantt_tooltip' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/ext/dhtmlxgantt_undo' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/locale/locale_ar' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/locale/locale_be' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/locale/locale_ca' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/locale/locale_cn' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/locale/locale_cs' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/locale/locale_da' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/locale/locale_de' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/locale/locale_el' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/locale/locale_es' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/locale/locale_fa' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/locale/locale_fi' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/locale/locale_fr' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/locale/locale_he' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/locale/locale_hr' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/locale/locale_hu' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/locale/locale_id' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/locale/locale_it' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/locale/locale_jp' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/locale/locale_kr' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/locale/locale_nb' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/locale/locale_nl' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/locale/locale_no' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/locale/locale_pl' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/locale/locale_pt' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/locale/locale_ro' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/locale/locale_ru' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/locale/locale_si' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/locale/locale_sk' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/locale/locale_sv' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/locale/locale_tr' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/locale/locale_ua' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/locale/locale' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/dhtmlxgantt' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/ext/dhtmlxgantt_csp' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/ext/dhtmlxgantt_fullscreen' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/ext/dhtmlxgantt_keyboard_navigation' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/ext/dhtmlxgantt_marker' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/ext/dhtmlxgantt_multiselect' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/ext/dhtmlxgantt_quick_info' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/ext/dhtmlxgantt_smart_rendering' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/ext/dhtmlxgantt_tooltip' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/ext/dhtmlxgantt_undo' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/locale/locale_ar' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/locale/locale_be' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/locale/locale_ca' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/locale/locale_cn' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/locale/locale_cs' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/locale/locale_da' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/locale/locale_de' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/locale/locale_el' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/locale/locale_es' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/locale/locale_fa' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/locale/locale_fi' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/locale/locale_fr' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/locale/locale_he' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/locale/locale_hr' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/locale/locale_hu' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/locale/locale_id' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/locale/locale_it' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/locale/locale_jp' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/locale/locale_kr' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/locale/locale_nb' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/locale/locale_nl' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/locale/locale_no' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/locale/locale_pl' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/locale/locale_pt' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/locale/locale_ro' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/locale/locale_ru' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/locale/locale_si' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/locale/locale_sk' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/locale/locale_sv' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/locale/locale_tr' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/locale/locale_ua' {
  declare module.exports: any;
}

declare module 'dhtmlx-gantt/codebase/sources/locale/locale' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dhtmlx-gantt/codebase/dhtmlxgantt.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/dhtmlxgantt'>;
}
declare module 'dhtmlx-gantt/codebase/ext/dhtmlxgantt_csp.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/ext/dhtmlxgantt_csp'>;
}
declare module 'dhtmlx-gantt/codebase/ext/dhtmlxgantt_fullscreen.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/ext/dhtmlxgantt_fullscreen'>;
}
declare module 'dhtmlx-gantt/codebase/ext/dhtmlxgantt_keyboard_navigation.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/ext/dhtmlxgantt_keyboard_navigation'>;
}
declare module 'dhtmlx-gantt/codebase/ext/dhtmlxgantt_marker.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/ext/dhtmlxgantt_marker'>;
}
declare module 'dhtmlx-gantt/codebase/ext/dhtmlxgantt_multiselect.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/ext/dhtmlxgantt_multiselect'>;
}
declare module 'dhtmlx-gantt/codebase/ext/dhtmlxgantt_quick_info.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/ext/dhtmlxgantt_quick_info'>;
}
declare module 'dhtmlx-gantt/codebase/ext/dhtmlxgantt_smart_rendering.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/ext/dhtmlxgantt_smart_rendering'>;
}
declare module 'dhtmlx-gantt/codebase/ext/dhtmlxgantt_tooltip.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/ext/dhtmlxgantt_tooltip'>;
}
declare module 'dhtmlx-gantt/codebase/ext/dhtmlxgantt_undo.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/ext/dhtmlxgantt_undo'>;
}
declare module 'dhtmlx-gantt/codebase/locale/locale_ar.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/locale/locale_ar'>;
}
declare module 'dhtmlx-gantt/codebase/locale/locale_be.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/locale/locale_be'>;
}
declare module 'dhtmlx-gantt/codebase/locale/locale_ca.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/locale/locale_ca'>;
}
declare module 'dhtmlx-gantt/codebase/locale/locale_cn.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/locale/locale_cn'>;
}
declare module 'dhtmlx-gantt/codebase/locale/locale_cs.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/locale/locale_cs'>;
}
declare module 'dhtmlx-gantt/codebase/locale/locale_da.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/locale/locale_da'>;
}
declare module 'dhtmlx-gantt/codebase/locale/locale_de.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/locale/locale_de'>;
}
declare module 'dhtmlx-gantt/codebase/locale/locale_el.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/locale/locale_el'>;
}
declare module 'dhtmlx-gantt/codebase/locale/locale_es.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/locale/locale_es'>;
}
declare module 'dhtmlx-gantt/codebase/locale/locale_fa.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/locale/locale_fa'>;
}
declare module 'dhtmlx-gantt/codebase/locale/locale_fi.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/locale/locale_fi'>;
}
declare module 'dhtmlx-gantt/codebase/locale/locale_fr.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/locale/locale_fr'>;
}
declare module 'dhtmlx-gantt/codebase/locale/locale_he.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/locale/locale_he'>;
}
declare module 'dhtmlx-gantt/codebase/locale/locale_hr.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/locale/locale_hr'>;
}
declare module 'dhtmlx-gantt/codebase/locale/locale_hu.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/locale/locale_hu'>;
}
declare module 'dhtmlx-gantt/codebase/locale/locale_id.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/locale/locale_id'>;
}
declare module 'dhtmlx-gantt/codebase/locale/locale_it.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/locale/locale_it'>;
}
declare module 'dhtmlx-gantt/codebase/locale/locale_jp.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/locale/locale_jp'>;
}
declare module 'dhtmlx-gantt/codebase/locale/locale_kr.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/locale/locale_kr'>;
}
declare module 'dhtmlx-gantt/codebase/locale/locale_nb.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/locale/locale_nb'>;
}
declare module 'dhtmlx-gantt/codebase/locale/locale_nl.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/locale/locale_nl'>;
}
declare module 'dhtmlx-gantt/codebase/locale/locale_no.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/locale/locale_no'>;
}
declare module 'dhtmlx-gantt/codebase/locale/locale_pl.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/locale/locale_pl'>;
}
declare module 'dhtmlx-gantt/codebase/locale/locale_pt.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/locale/locale_pt'>;
}
declare module 'dhtmlx-gantt/codebase/locale/locale_ro.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/locale/locale_ro'>;
}
declare module 'dhtmlx-gantt/codebase/locale/locale_ru.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/locale/locale_ru'>;
}
declare module 'dhtmlx-gantt/codebase/locale/locale_si.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/locale/locale_si'>;
}
declare module 'dhtmlx-gantt/codebase/locale/locale_sk.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/locale/locale_sk'>;
}
declare module 'dhtmlx-gantt/codebase/locale/locale_sv.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/locale/locale_sv'>;
}
declare module 'dhtmlx-gantt/codebase/locale/locale_tr.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/locale/locale_tr'>;
}
declare module 'dhtmlx-gantt/codebase/locale/locale_ua.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/locale/locale_ua'>;
}
declare module 'dhtmlx-gantt/codebase/locale/locale.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/locale/locale'>;
}
declare module 'dhtmlx-gantt/codebase/sources/dhtmlxgantt.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/dhtmlxgantt'>;
}
declare module 'dhtmlx-gantt/codebase/sources/ext/dhtmlxgantt_csp.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/ext/dhtmlxgantt_csp'>;
}
declare module 'dhtmlx-gantt/codebase/sources/ext/dhtmlxgantt_fullscreen.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/ext/dhtmlxgantt_fullscreen'>;
}
declare module 'dhtmlx-gantt/codebase/sources/ext/dhtmlxgantt_keyboard_navigation.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/ext/dhtmlxgantt_keyboard_navigation'>;
}
declare module 'dhtmlx-gantt/codebase/sources/ext/dhtmlxgantt_marker.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/ext/dhtmlxgantt_marker'>;
}
declare module 'dhtmlx-gantt/codebase/sources/ext/dhtmlxgantt_multiselect.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/ext/dhtmlxgantt_multiselect'>;
}
declare module 'dhtmlx-gantt/codebase/sources/ext/dhtmlxgantt_quick_info.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/ext/dhtmlxgantt_quick_info'>;
}
declare module 'dhtmlx-gantt/codebase/sources/ext/dhtmlxgantt_smart_rendering.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/ext/dhtmlxgantt_smart_rendering'>;
}
declare module 'dhtmlx-gantt/codebase/sources/ext/dhtmlxgantt_tooltip.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/ext/dhtmlxgantt_tooltip'>;
}
declare module 'dhtmlx-gantt/codebase/sources/ext/dhtmlxgantt_undo.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/ext/dhtmlxgantt_undo'>;
}
declare module 'dhtmlx-gantt/codebase/sources/locale/locale_ar.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/locale/locale_ar'>;
}
declare module 'dhtmlx-gantt/codebase/sources/locale/locale_be.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/locale/locale_be'>;
}
declare module 'dhtmlx-gantt/codebase/sources/locale/locale_ca.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/locale/locale_ca'>;
}
declare module 'dhtmlx-gantt/codebase/sources/locale/locale_cn.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/locale/locale_cn'>;
}
declare module 'dhtmlx-gantt/codebase/sources/locale/locale_cs.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/locale/locale_cs'>;
}
declare module 'dhtmlx-gantt/codebase/sources/locale/locale_da.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/locale/locale_da'>;
}
declare module 'dhtmlx-gantt/codebase/sources/locale/locale_de.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/locale/locale_de'>;
}
declare module 'dhtmlx-gantt/codebase/sources/locale/locale_el.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/locale/locale_el'>;
}
declare module 'dhtmlx-gantt/codebase/sources/locale/locale_es.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/locale/locale_es'>;
}
declare module 'dhtmlx-gantt/codebase/sources/locale/locale_fa.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/locale/locale_fa'>;
}
declare module 'dhtmlx-gantt/codebase/sources/locale/locale_fi.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/locale/locale_fi'>;
}
declare module 'dhtmlx-gantt/codebase/sources/locale/locale_fr.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/locale/locale_fr'>;
}
declare module 'dhtmlx-gantt/codebase/sources/locale/locale_he.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/locale/locale_he'>;
}
declare module 'dhtmlx-gantt/codebase/sources/locale/locale_hr.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/locale/locale_hr'>;
}
declare module 'dhtmlx-gantt/codebase/sources/locale/locale_hu.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/locale/locale_hu'>;
}
declare module 'dhtmlx-gantt/codebase/sources/locale/locale_id.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/locale/locale_id'>;
}
declare module 'dhtmlx-gantt/codebase/sources/locale/locale_it.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/locale/locale_it'>;
}
declare module 'dhtmlx-gantt/codebase/sources/locale/locale_jp.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/locale/locale_jp'>;
}
declare module 'dhtmlx-gantt/codebase/sources/locale/locale_kr.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/locale/locale_kr'>;
}
declare module 'dhtmlx-gantt/codebase/sources/locale/locale_nb.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/locale/locale_nb'>;
}
declare module 'dhtmlx-gantt/codebase/sources/locale/locale_nl.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/locale/locale_nl'>;
}
declare module 'dhtmlx-gantt/codebase/sources/locale/locale_no.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/locale/locale_no'>;
}
declare module 'dhtmlx-gantt/codebase/sources/locale/locale_pl.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/locale/locale_pl'>;
}
declare module 'dhtmlx-gantt/codebase/sources/locale/locale_pt.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/locale/locale_pt'>;
}
declare module 'dhtmlx-gantt/codebase/sources/locale/locale_ro.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/locale/locale_ro'>;
}
declare module 'dhtmlx-gantt/codebase/sources/locale/locale_ru.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/locale/locale_ru'>;
}
declare module 'dhtmlx-gantt/codebase/sources/locale/locale_si.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/locale/locale_si'>;
}
declare module 'dhtmlx-gantt/codebase/sources/locale/locale_sk.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/locale/locale_sk'>;
}
declare module 'dhtmlx-gantt/codebase/sources/locale/locale_sv.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/locale/locale_sv'>;
}
declare module 'dhtmlx-gantt/codebase/sources/locale/locale_tr.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/locale/locale_tr'>;
}
declare module 'dhtmlx-gantt/codebase/sources/locale/locale_ua.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/locale/locale_ua'>;
}
declare module 'dhtmlx-gantt/codebase/sources/locale/locale.js' {
  declare module.exports: $Exports<'dhtmlx-gantt/codebase/sources/locale/locale'>;
}
