// flow-typed signature: 9a7fcbfaba1c2012d2a639b093f8cfd6
// flow-typed version: <<STUB>>/greenlet_v^1.0.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'greenlet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'greenlet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'greenlet/dist/greenlet' {
  declare module.exports: any;
}

declare module 'greenlet/dist/greenlet.m' {
  declare module.exports: any;
}

declare module 'greenlet/dist/greenlet.umd' {
  declare module.exports: any;
}

declare module 'greenlet/greenlet' {
  declare module.exports: any;
}

// Filename aliases
declare module 'greenlet/dist/greenlet.js' {
  declare module.exports: $Exports<'greenlet/dist/greenlet'>;
}
declare module 'greenlet/dist/greenlet.m.js' {
  declare module.exports: $Exports<'greenlet/dist/greenlet.m'>;
}
declare module 'greenlet/dist/greenlet.umd.js' {
  declare module.exports: $Exports<'greenlet/dist/greenlet.umd'>;
}
declare module 'greenlet/greenlet.js' {
  declare module.exports: $Exports<'greenlet/greenlet'>;
}
