// flow-typed signature: 2813e65be7dd85675185daa59308bdeb
// flow-typed version: <<STUB>>/html2canvas_v^1.0.0-alpha.12/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html2canvas'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html2canvas' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'html2canvas/dist/html2canvas' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/html2canvas.min' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/Angle' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/Bounds' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/Clone' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/Color' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/drawing/BezierCurve' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/drawing/Circle' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/drawing/Path' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/drawing/Size' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/drawing/Vector' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/Feature' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/Font' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/Gradient' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/index' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/Input' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/Length' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/ListItem' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/Logger' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/NodeContainer' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/NodeParser' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/parsing/background' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/parsing/border' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/parsing/borderRadius' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/parsing/display' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/parsing/float' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/parsing/font' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/parsing/letterSpacing' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/parsing/lineBreak' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/parsing/listStyle' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/parsing/margin' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/parsing/overflow' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/parsing/overflowWrap' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/parsing/padding' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/parsing/position' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/parsing/textDecoration' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/parsing/textShadow' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/parsing/textTransform' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/parsing/transform' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/parsing/visibility' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/parsing/word-break' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/parsing/zIndex' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/Proxy' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/PseudoNodeContent' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/Renderer' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/renderer/CanvasRenderer' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/renderer/ForeignObjectRenderer' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/renderer/RefTestRenderer' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/ResourceLoader' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/StackingContext' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/TextBounds' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/TextContainer' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/Unicode' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/Util' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/npm/Window' {
  declare module.exports: any;
}

declare module 'html2canvas/flow-typed/myLibDef' {
  declare module.exports: any;
}

// Filename aliases
declare module 'html2canvas/dist/html2canvas.js' {
  declare module.exports: $Exports<'html2canvas/dist/html2canvas'>;
}
declare module 'html2canvas/dist/html2canvas.min.js' {
  declare module.exports: $Exports<'html2canvas/dist/html2canvas.min'>;
}
declare module 'html2canvas/dist/npm/Angle.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/Angle'>;
}
declare module 'html2canvas/dist/npm/Bounds.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/Bounds'>;
}
declare module 'html2canvas/dist/npm/Clone.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/Clone'>;
}
declare module 'html2canvas/dist/npm/Color.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/Color'>;
}
declare module 'html2canvas/dist/npm/drawing/BezierCurve.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/drawing/BezierCurve'>;
}
declare module 'html2canvas/dist/npm/drawing/Circle.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/drawing/Circle'>;
}
declare module 'html2canvas/dist/npm/drawing/Path.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/drawing/Path'>;
}
declare module 'html2canvas/dist/npm/drawing/Size.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/drawing/Size'>;
}
declare module 'html2canvas/dist/npm/drawing/Vector.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/drawing/Vector'>;
}
declare module 'html2canvas/dist/npm/Feature.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/Feature'>;
}
declare module 'html2canvas/dist/npm/Font.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/Font'>;
}
declare module 'html2canvas/dist/npm/Gradient.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/Gradient'>;
}
declare module 'html2canvas/dist/npm/index.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/index'>;
}
declare module 'html2canvas/dist/npm/Input.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/Input'>;
}
declare module 'html2canvas/dist/npm/Length.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/Length'>;
}
declare module 'html2canvas/dist/npm/ListItem.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/ListItem'>;
}
declare module 'html2canvas/dist/npm/Logger.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/Logger'>;
}
declare module 'html2canvas/dist/npm/NodeContainer.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/NodeContainer'>;
}
declare module 'html2canvas/dist/npm/NodeParser.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/NodeParser'>;
}
declare module 'html2canvas/dist/npm/parsing/background.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/parsing/background'>;
}
declare module 'html2canvas/dist/npm/parsing/border.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/parsing/border'>;
}
declare module 'html2canvas/dist/npm/parsing/borderRadius.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/parsing/borderRadius'>;
}
declare module 'html2canvas/dist/npm/parsing/display.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/parsing/display'>;
}
declare module 'html2canvas/dist/npm/parsing/float.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/parsing/float'>;
}
declare module 'html2canvas/dist/npm/parsing/font.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/parsing/font'>;
}
declare module 'html2canvas/dist/npm/parsing/letterSpacing.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/parsing/letterSpacing'>;
}
declare module 'html2canvas/dist/npm/parsing/lineBreak.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/parsing/lineBreak'>;
}
declare module 'html2canvas/dist/npm/parsing/listStyle.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/parsing/listStyle'>;
}
declare module 'html2canvas/dist/npm/parsing/margin.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/parsing/margin'>;
}
declare module 'html2canvas/dist/npm/parsing/overflow.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/parsing/overflow'>;
}
declare module 'html2canvas/dist/npm/parsing/overflowWrap.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/parsing/overflowWrap'>;
}
declare module 'html2canvas/dist/npm/parsing/padding.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/parsing/padding'>;
}
declare module 'html2canvas/dist/npm/parsing/position.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/parsing/position'>;
}
declare module 'html2canvas/dist/npm/parsing/textDecoration.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/parsing/textDecoration'>;
}
declare module 'html2canvas/dist/npm/parsing/textShadow.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/parsing/textShadow'>;
}
declare module 'html2canvas/dist/npm/parsing/textTransform.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/parsing/textTransform'>;
}
declare module 'html2canvas/dist/npm/parsing/transform.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/parsing/transform'>;
}
declare module 'html2canvas/dist/npm/parsing/visibility.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/parsing/visibility'>;
}
declare module 'html2canvas/dist/npm/parsing/word-break.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/parsing/word-break'>;
}
declare module 'html2canvas/dist/npm/parsing/zIndex.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/parsing/zIndex'>;
}
declare module 'html2canvas/dist/npm/Proxy.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/Proxy'>;
}
declare module 'html2canvas/dist/npm/PseudoNodeContent.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/PseudoNodeContent'>;
}
declare module 'html2canvas/dist/npm/Renderer.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/Renderer'>;
}
declare module 'html2canvas/dist/npm/renderer/CanvasRenderer.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/renderer/CanvasRenderer'>;
}
declare module 'html2canvas/dist/npm/renderer/ForeignObjectRenderer.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/renderer/ForeignObjectRenderer'>;
}
declare module 'html2canvas/dist/npm/renderer/RefTestRenderer.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/renderer/RefTestRenderer'>;
}
declare module 'html2canvas/dist/npm/ResourceLoader.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/ResourceLoader'>;
}
declare module 'html2canvas/dist/npm/StackingContext.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/StackingContext'>;
}
declare module 'html2canvas/dist/npm/TextBounds.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/TextBounds'>;
}
declare module 'html2canvas/dist/npm/TextContainer.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/TextContainer'>;
}
declare module 'html2canvas/dist/npm/Unicode.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/Unicode'>;
}
declare module 'html2canvas/dist/npm/Util.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/Util'>;
}
declare module 'html2canvas/dist/npm/Window.js' {
  declare module.exports: $Exports<'html2canvas/dist/npm/Window'>;
}
declare module 'html2canvas/flow-typed/myLibDef.js' {
  declare module.exports: $Exports<'html2canvas/flow-typed/myLibDef'>;
}
