// flow-typed signature: 20c17c79fb4de16b0913a72c6941aa48
// flow-typed version: <<STUB>>/jsonexport_v^2.4.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsonexport'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsonexport' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsonexport/bin/builddist' {
  declare module.exports: any;
}

declare module 'jsonexport/bin/jsonexport' {
  declare module.exports: any;
}

declare module 'jsonexport/dist/core/eol' {
  declare module.exports: any;
}

declare module 'jsonexport/dist/core/escape-delimiters' {
  declare module.exports: any;
}

declare module 'jsonexport/dist/core/helper' {
  declare module.exports: any;
}

declare module 'jsonexport/dist/core/join-rows' {
  declare module.exports: any;
}

declare module 'jsonexport/dist/core/stream' {
  declare module.exports: any;
}

declare module 'jsonexport/dist/index' {
  declare module.exports: any;
}

declare module 'jsonexport/dist/parser/csv' {
  declare module.exports: any;
}

declare module 'jsonexport/dist/parser/handler' {
  declare module.exports: any;
}

declare module 'jsonexport/examples/simple' {
  declare module.exports: any;
}

declare module 'jsonexport/lib/core/eol' {
  declare module.exports: any;
}

declare module 'jsonexport/lib/core/escape-delimiters' {
  declare module.exports: any;
}

declare module 'jsonexport/lib/core/helper' {
  declare module.exports: any;
}

declare module 'jsonexport/lib/core/join-rows' {
  declare module.exports: any;
}

declare module 'jsonexport/lib/core/stream' {
  declare module.exports: any;
}

declare module 'jsonexport/lib/index' {
  declare module.exports: any;
}

declare module 'jsonexport/lib/parser/csv' {
  declare module.exports: any;
}

declare module 'jsonexport/lib/parser/handler' {
  declare module.exports: any;
}

declare module 'jsonexport/tests/array' {
  declare module.exports: any;
}

declare module 'jsonexport/tests/escape-delimiters' {
  declare module.exports: any;
}

declare module 'jsonexport/tests/join-rows' {
  declare module.exports: any;
}

declare module 'jsonexport/tests/object' {
  declare module.exports: any;
}

declare module 'jsonexport/tests/options' {
  declare module.exports: any;
}

declare module 'jsonexport/tests/stream' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsonexport/bin/builddist.js' {
  declare module.exports: $Exports<'jsonexport/bin/builddist'>;
}
declare module 'jsonexport/bin/jsonexport.js' {
  declare module.exports: $Exports<'jsonexport/bin/jsonexport'>;
}
declare module 'jsonexport/dist/core/eol.js' {
  declare module.exports: $Exports<'jsonexport/dist/core/eol'>;
}
declare module 'jsonexport/dist/core/escape-delimiters.js' {
  declare module.exports: $Exports<'jsonexport/dist/core/escape-delimiters'>;
}
declare module 'jsonexport/dist/core/helper.js' {
  declare module.exports: $Exports<'jsonexport/dist/core/helper'>;
}
declare module 'jsonexport/dist/core/join-rows.js' {
  declare module.exports: $Exports<'jsonexport/dist/core/join-rows'>;
}
declare module 'jsonexport/dist/core/stream.js' {
  declare module.exports: $Exports<'jsonexport/dist/core/stream'>;
}
declare module 'jsonexport/dist/index.js' {
  declare module.exports: $Exports<'jsonexport/dist/index'>;
}
declare module 'jsonexport/dist/parser/csv.js' {
  declare module.exports: $Exports<'jsonexport/dist/parser/csv'>;
}
declare module 'jsonexport/dist/parser/handler.js' {
  declare module.exports: $Exports<'jsonexport/dist/parser/handler'>;
}
declare module 'jsonexport/examples/simple.js' {
  declare module.exports: $Exports<'jsonexport/examples/simple'>;
}
declare module 'jsonexport/lib/core/eol.js' {
  declare module.exports: $Exports<'jsonexport/lib/core/eol'>;
}
declare module 'jsonexport/lib/core/escape-delimiters.js' {
  declare module.exports: $Exports<'jsonexport/lib/core/escape-delimiters'>;
}
declare module 'jsonexport/lib/core/helper.js' {
  declare module.exports: $Exports<'jsonexport/lib/core/helper'>;
}
declare module 'jsonexport/lib/core/join-rows.js' {
  declare module.exports: $Exports<'jsonexport/lib/core/join-rows'>;
}
declare module 'jsonexport/lib/core/stream.js' {
  declare module.exports: $Exports<'jsonexport/lib/core/stream'>;
}
declare module 'jsonexport/lib/index.js' {
  declare module.exports: $Exports<'jsonexport/lib/index'>;
}
declare module 'jsonexport/lib/parser/csv.js' {
  declare module.exports: $Exports<'jsonexport/lib/parser/csv'>;
}
declare module 'jsonexport/lib/parser/handler.js' {
  declare module.exports: $Exports<'jsonexport/lib/parser/handler'>;
}
declare module 'jsonexport/tests/array.js' {
  declare module.exports: $Exports<'jsonexport/tests/array'>;
}
declare module 'jsonexport/tests/escape-delimiters.js' {
  declare module.exports: $Exports<'jsonexport/tests/escape-delimiters'>;
}
declare module 'jsonexport/tests/join-rows.js' {
  declare module.exports: $Exports<'jsonexport/tests/join-rows'>;
}
declare module 'jsonexport/tests/object.js' {
  declare module.exports: $Exports<'jsonexport/tests/object'>;
}
declare module 'jsonexport/tests/options.js' {
  declare module.exports: $Exports<'jsonexport/tests/options'>;
}
declare module 'jsonexport/tests/stream.js' {
  declare module.exports: $Exports<'jsonexport/tests/stream'>;
}
