// flow-typed signature: a0c00980be9abdaac0975c0d0077738c
// flow-typed version: <<STUB>>/leaflet-measure_v^3.1.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'leaflet-measure'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'leaflet-measure' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'leaflet-measure/dist/leaflet-measure.ca' {
  declare module.exports: any;
}

declare module 'leaflet-measure/dist/leaflet-measure.cn' {
  declare module.exports: any;
}

declare module 'leaflet-measure/dist/leaflet-measure.cz' {
  declare module.exports: any;
}

declare module 'leaflet-measure/dist/leaflet-measure.da' {
  declare module.exports: any;
}

declare module 'leaflet-measure/dist/leaflet-measure.de_CH' {
  declare module.exports: any;
}

declare module 'leaflet-measure/dist/leaflet-measure.de' {
  declare module.exports: any;
}

declare module 'leaflet-measure/dist/leaflet-measure.en_UK' {
  declare module.exports: any;
}

declare module 'leaflet-measure/dist/leaflet-measure.en' {
  declare module.exports: any;
}

declare module 'leaflet-measure/dist/leaflet-measure.es' {
  declare module.exports: any;
}

declare module 'leaflet-measure/dist/leaflet-measure.fa' {
  declare module.exports: any;
}

declare module 'leaflet-measure/dist/leaflet-measure.fil_PH' {
  declare module.exports: any;
}

declare module 'leaflet-measure/dist/leaflet-measure.fr' {
  declare module.exports: any;
}

declare module 'leaflet-measure/dist/leaflet-measure.hu' {
  declare module.exports: any;
}

declare module 'leaflet-measure/dist/leaflet-measure.it' {
  declare module.exports: any;
}

declare module 'leaflet-measure/dist/leaflet-measure' {
  declare module.exports: any;
}

declare module 'leaflet-measure/dist/leaflet-measure.nl' {
  declare module.exports: any;
}

declare module 'leaflet-measure/dist/leaflet-measure.pl' {
  declare module.exports: any;
}

declare module 'leaflet-measure/dist/leaflet-measure.pt_BR' {
  declare module.exports: any;
}

declare module 'leaflet-measure/dist/leaflet-measure.pt_PT' {
  declare module.exports: any;
}

declare module 'leaflet-measure/dist/leaflet-measure.ro' {
  declare module.exports: any;
}

declare module 'leaflet-measure/dist/leaflet-measure.ru' {
  declare module.exports: any;
}

declare module 'leaflet-measure/dist/leaflet-measure.sk' {
  declare module.exports: any;
}

declare module 'leaflet-measure/dist/leaflet-measure.sl' {
  declare module.exports: any;
}

declare module 'leaflet-measure/dist/leaflet-measure.sv' {
  declare module.exports: any;
}

declare module 'leaflet-measure/dist/leaflet-measure.tr' {
  declare module.exports: any;
}

declare module 'leaflet-measure/src/calc' {
  declare module.exports: any;
}

declare module 'leaflet-measure/src/dom' {
  declare module.exports: any;
}

declare module 'leaflet-measure/src/leaflet-measure' {
  declare module.exports: any;
}

declare module 'leaflet-measure/src/symbology' {
  declare module.exports: any;
}

declare module 'leaflet-measure/src/templates/index' {
  declare module.exports: any;
}

declare module 'leaflet-measure/src/units' {
  declare module.exports: any;
}

declare module 'leaflet-measure/src/utils' {
  declare module.exports: any;
}

declare module 'leaflet-measure/webpack.dev' {
  declare module.exports: any;
}

declare module 'leaflet-measure/webpack.prod' {
  declare module.exports: any;
}

// Filename aliases
declare module 'leaflet-measure/dist/leaflet-measure.ca.js' {
  declare module.exports: $Exports<'leaflet-measure/dist/leaflet-measure.ca'>;
}
declare module 'leaflet-measure/dist/leaflet-measure.cn.js' {
  declare module.exports: $Exports<'leaflet-measure/dist/leaflet-measure.cn'>;
}
declare module 'leaflet-measure/dist/leaflet-measure.cz.js' {
  declare module.exports: $Exports<'leaflet-measure/dist/leaflet-measure.cz'>;
}
declare module 'leaflet-measure/dist/leaflet-measure.da.js' {
  declare module.exports: $Exports<'leaflet-measure/dist/leaflet-measure.da'>;
}
declare module 'leaflet-measure/dist/leaflet-measure.de_CH.js' {
  declare module.exports: $Exports<'leaflet-measure/dist/leaflet-measure.de_CH'>;
}
declare module 'leaflet-measure/dist/leaflet-measure.de.js' {
  declare module.exports: $Exports<'leaflet-measure/dist/leaflet-measure.de'>;
}
declare module 'leaflet-measure/dist/leaflet-measure.en_UK.js' {
  declare module.exports: $Exports<'leaflet-measure/dist/leaflet-measure.en_UK'>;
}
declare module 'leaflet-measure/dist/leaflet-measure.en.js' {
  declare module.exports: $Exports<'leaflet-measure/dist/leaflet-measure.en'>;
}
declare module 'leaflet-measure/dist/leaflet-measure.es.js' {
  declare module.exports: $Exports<'leaflet-measure/dist/leaflet-measure.es'>;
}
declare module 'leaflet-measure/dist/leaflet-measure.fa.js' {
  declare module.exports: $Exports<'leaflet-measure/dist/leaflet-measure.fa'>;
}
declare module 'leaflet-measure/dist/leaflet-measure.fil_PH.js' {
  declare module.exports: $Exports<'leaflet-measure/dist/leaflet-measure.fil_PH'>;
}
declare module 'leaflet-measure/dist/leaflet-measure.fr.js' {
  declare module.exports: $Exports<'leaflet-measure/dist/leaflet-measure.fr'>;
}
declare module 'leaflet-measure/dist/leaflet-measure.hu.js' {
  declare module.exports: $Exports<'leaflet-measure/dist/leaflet-measure.hu'>;
}
declare module 'leaflet-measure/dist/leaflet-measure.it.js' {
  declare module.exports: $Exports<'leaflet-measure/dist/leaflet-measure.it'>;
}
declare module 'leaflet-measure/dist/leaflet-measure.js' {
  declare module.exports: $Exports<'leaflet-measure/dist/leaflet-measure'>;
}
declare module 'leaflet-measure/dist/leaflet-measure.nl.js' {
  declare module.exports: $Exports<'leaflet-measure/dist/leaflet-measure.nl'>;
}
declare module 'leaflet-measure/dist/leaflet-measure.pl.js' {
  declare module.exports: $Exports<'leaflet-measure/dist/leaflet-measure.pl'>;
}
declare module 'leaflet-measure/dist/leaflet-measure.pt_BR.js' {
  declare module.exports: $Exports<'leaflet-measure/dist/leaflet-measure.pt_BR'>;
}
declare module 'leaflet-measure/dist/leaflet-measure.pt_PT.js' {
  declare module.exports: $Exports<'leaflet-measure/dist/leaflet-measure.pt_PT'>;
}
declare module 'leaflet-measure/dist/leaflet-measure.ro.js' {
  declare module.exports: $Exports<'leaflet-measure/dist/leaflet-measure.ro'>;
}
declare module 'leaflet-measure/dist/leaflet-measure.ru.js' {
  declare module.exports: $Exports<'leaflet-measure/dist/leaflet-measure.ru'>;
}
declare module 'leaflet-measure/dist/leaflet-measure.sk.js' {
  declare module.exports: $Exports<'leaflet-measure/dist/leaflet-measure.sk'>;
}
declare module 'leaflet-measure/dist/leaflet-measure.sl.js' {
  declare module.exports: $Exports<'leaflet-measure/dist/leaflet-measure.sl'>;
}
declare module 'leaflet-measure/dist/leaflet-measure.sv.js' {
  declare module.exports: $Exports<'leaflet-measure/dist/leaflet-measure.sv'>;
}
declare module 'leaflet-measure/dist/leaflet-measure.tr.js' {
  declare module.exports: $Exports<'leaflet-measure/dist/leaflet-measure.tr'>;
}
declare module 'leaflet-measure/src/calc.js' {
  declare module.exports: $Exports<'leaflet-measure/src/calc'>;
}
declare module 'leaflet-measure/src/dom.js' {
  declare module.exports: $Exports<'leaflet-measure/src/dom'>;
}
declare module 'leaflet-measure/src/leaflet-measure.js' {
  declare module.exports: $Exports<'leaflet-measure/src/leaflet-measure'>;
}
declare module 'leaflet-measure/src/symbology.js' {
  declare module.exports: $Exports<'leaflet-measure/src/symbology'>;
}
declare module 'leaflet-measure/src/templates/index.js' {
  declare module.exports: $Exports<'leaflet-measure/src/templates/index'>;
}
declare module 'leaflet-measure/src/units.js' {
  declare module.exports: $Exports<'leaflet-measure/src/units'>;
}
declare module 'leaflet-measure/src/utils.js' {
  declare module.exports: $Exports<'leaflet-measure/src/utils'>;
}
declare module 'leaflet-measure/webpack.dev.js' {
  declare module.exports: $Exports<'leaflet-measure/webpack.dev'>;
}
declare module 'leaflet-measure/webpack.prod.js' {
  declare module.exports: $Exports<'leaflet-measure/webpack.prod'>;
}
