// flow-typed signature: 8e09d2a8e70e82a6e2b40c03c09ac40d
// flow-typed version: <<STUB>>/primeicons_v^1.0.0-beta.9/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'primeicons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'primeicons' {
  declare module.exports: any;
}
