// flow-typed signature: e807ced2053f6d6399077738df8fa825
// flow-typed version: <<STUB>>/primereact_v^1.6.2/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'primereact'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'primereact' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'primereact/components/accordion/Accordion' {
  declare module.exports: any;
}

declare module 'primereact/components/autocomplete/AutoComplete' {
  declare module.exports: any;
}

declare module 'primereact/components/autocomplete/AutoCompletePanel' {
  declare module.exports: any;
}

declare module 'primereact/components/breadcrumb/BreadCrumb' {
  declare module.exports: any;
}

declare module 'primereact/components/button/Button' {
  declare module.exports: any;
}

declare module 'primereact/components/calendar/Calendar' {
  declare module.exports: any;
}

declare module 'primereact/components/calendar/CalendarPanel' {
  declare module.exports: any;
}

declare module 'primereact/components/captcha/Captcha' {
  declare module.exports: any;
}

declare module 'primereact/components/card/Card' {
  declare module.exports: any;
}

declare module 'primereact/components/chart/Chart' {
  declare module.exports: any;
}

declare module 'primereact/components/checkbox/Checkbox' {
  declare module.exports: any;
}

declare module 'primereact/components/chips/Chips' {
  declare module.exports: any;
}

declare module 'primereact/components/colorpicker/ColorPicker' {
  declare module.exports: any;
}

declare module 'primereact/components/colorpicker/ColorPickerPanel' {
  declare module.exports: any;
}

declare module 'primereact/components/column/Column' {
  declare module.exports: any;
}

declare module 'primereact/components/columngroup/ColumnGroup' {
  declare module.exports: any;
}

declare module 'primereact/components/contextmenu/ContextMenu' {
  declare module.exports: any;
}

declare module 'primereact/components/datagrid/DataGrid' {
  declare module.exports: any;
}

declare module 'primereact/components/datalist/DataList' {
  declare module.exports: any;
}

declare module 'primereact/components/datascroller/DataScroller' {
  declare module.exports: any;
}

declare module 'primereact/components/datatable/BodyCell' {
  declare module.exports: any;
}

declare module 'primereact/components/datatable/BodyRow' {
  declare module.exports: any;
}

declare module 'primereact/components/datatable/DataTable' {
  declare module.exports: any;
}

declare module 'primereact/components/datatable/FooterCell' {
  declare module.exports: any;
}

declare module 'primereact/components/datatable/HeaderCell' {
  declare module.exports: any;
}

declare module 'primereact/components/datatable/RowCheckbox' {
  declare module.exports: any;
}

declare module 'primereact/components/datatable/RowRadioButton' {
  declare module.exports: any;
}

declare module 'primereact/components/datatable/ScrollableView' {
  declare module.exports: any;
}

declare module 'primereact/components/datatable/TableBody' {
  declare module.exports: any;
}

declare module 'primereact/components/datatable/TableFooter' {
  declare module.exports: any;
}

declare module 'primereact/components/datatable/TableHeader' {
  declare module.exports: any;
}

declare module 'primereact/components/dataview/DataView' {
  declare module.exports: any;
}

declare module 'primereact/components/dialog/Dialog' {
  declare module.exports: any;
}

declare module 'primereact/components/dropdown/Dropdown' {
  declare module.exports: any;
}

declare module 'primereact/components/dropdown/DropdownItem' {
  declare module.exports: any;
}

declare module 'primereact/components/dropdown/DropdownPanel' {
  declare module.exports: any;
}

declare module 'primereact/components/editor/Editor' {
  declare module.exports: any;
}

declare module 'primereact/components/fieldset/Fieldset' {
  declare module.exports: any;
}

declare module 'primereact/components/fileupload/FileUpload' {
  declare module.exports: any;
}

declare module 'primereact/components/gmap/GMap' {
  declare module.exports: any;
}

declare module 'primereact/components/growl/Growl' {
  declare module.exports: any;
}

declare module 'primereact/components/growl/GrowlMessage' {
  declare module.exports: any;
}

declare module 'primereact/components/inputmask/InputMask' {
  declare module.exports: any;
}

declare module 'primereact/components/inputswitch/InputSwitch' {
  declare module.exports: any;
}

declare module 'primereact/components/inputtext/InputText' {
  declare module.exports: any;
}

declare module 'primereact/components/inputtextarea/InputTextarea' {
  declare module.exports: any;
}

declare module 'primereact/components/keyfilter/KeyFilter' {
  declare module.exports: any;
}

declare module 'primereact/components/lightbox/Lightbox' {
  declare module.exports: any;
}

declare module 'primereact/components/listbox/ListBox' {
  declare module.exports: any;
}

declare module 'primereact/components/listbox/ListBoxHeader' {
  declare module.exports: any;
}

declare module 'primereact/components/listbox/ListBoxItem' {
  declare module.exports: any;
}

declare module 'primereact/components/megamenu/MegaMenu' {
  declare module.exports: any;
}

declare module 'primereact/components/menu/Menu' {
  declare module.exports: any;
}

declare module 'primereact/components/menu/MenuItem' {
  declare module.exports: any;
}

declare module 'primereact/components/menubar/Menubar' {
  declare module.exports: any;
}

declare module 'primereact/components/message/Message' {
  declare module.exports: any;
}

declare module 'primereact/components/messages/Messages' {
  declare module.exports: any;
}

declare module 'primereact/components/messages/UIMessage' {
  declare module.exports: any;
}

declare module 'primereact/components/multiselect/MultiSelect' {
  declare module.exports: any;
}

declare module 'primereact/components/multiselect/MultiSelectHeader' {
  declare module.exports: any;
}

declare module 'primereact/components/multiselect/MultiSelectItem' {
  declare module.exports: any;
}

declare module 'primereact/components/multiselect/MultiSelectPanel' {
  declare module.exports: any;
}

declare module 'primereact/components/nestedmenu/NestedMenu' {
  declare module.exports: any;
}

declare module 'primereact/components/nestedmenu/NestedMenuItem' {
  declare module.exports: any;
}

declare module 'primereact/components/orderlist/OrderList' {
  declare module.exports: any;
}

declare module 'primereact/components/orderlist/OrderListControls' {
  declare module.exports: any;
}

declare module 'primereact/components/orderlist/OrderListSubList' {
  declare module.exports: any;
}

declare module 'primereact/components/organizationchart/OrganizationChart' {
  declare module.exports: any;
}

declare module 'primereact/components/overlaypanel/OverlayPanel' {
  declare module.exports: any;
}

declare module 'primereact/components/paginator/CurrentPageReport' {
  declare module.exports: any;
}

declare module 'primereact/components/paginator/FirstPageLink' {
  declare module.exports: any;
}

declare module 'primereact/components/paginator/LastPageLink' {
  declare module.exports: any;
}

declare module 'primereact/components/paginator/NextPageLink' {
  declare module.exports: any;
}

declare module 'primereact/components/paginator/PageLinks' {
  declare module.exports: any;
}

declare module 'primereact/components/paginator/Paginator' {
  declare module.exports: any;
}

declare module 'primereact/components/paginator/PrevPageLink' {
  declare module.exports: any;
}

declare module 'primereact/components/paginator/RowsPerPageDropdown' {
  declare module.exports: any;
}

declare module 'primereact/components/panel/Panel' {
  declare module.exports: any;
}

declare module 'primereact/components/panelmenu/PanelMenu' {
  declare module.exports: any;
}

declare module 'primereact/components/password/Password' {
  declare module.exports: any;
}

declare module 'primereact/components/picklist/PickList' {
  declare module.exports: any;
}

declare module 'primereact/components/picklist/PickListControls' {
  declare module.exports: any;
}

declare module 'primereact/components/picklist/PickListItem' {
  declare module.exports: any;
}

declare module 'primereact/components/picklist/PickListSubList' {
  declare module.exports: any;
}

declare module 'primereact/components/picklist/PickListTransferControls' {
  declare module.exports: any;
}

declare module 'primereact/components/progressbar/ProgressBar' {
  declare module.exports: any;
}

declare module 'primereact/components/progressspinner/ProgressSpinner' {
  declare module.exports: any;
}

declare module 'primereact/components/radiobutton/RadioButton' {
  declare module.exports: any;
}

declare module 'primereact/components/rating/Rating' {
  declare module.exports: any;
}

declare module 'primereact/components/row/Row' {
  declare module.exports: any;
}

declare module 'primereact/components/schedule/Schedule' {
  declare module.exports: any;
}

declare module 'primereact/components/scrollpanel/ScrollPanel' {
  declare module.exports: any;
}

declare module 'primereact/components/selectbutton/SelectButton' {
  declare module.exports: any;
}

declare module 'primereact/components/selectbutton/SelectButtonItem' {
  declare module.exports: any;
}

declare module 'primereact/components/sidebar/Sidebar' {
  declare module.exports: any;
}

declare module 'primereact/components/slidemenu/SlideMenu' {
  declare module.exports: any;
}

declare module 'primereact/components/slider/Slider' {
  declare module.exports: any;
}

declare module 'primereact/components/spinner/Spinner' {
  declare module.exports: any;
}

declare module 'primereact/components/splitbutton/SplitButton' {
  declare module.exports: any;
}

declare module 'primereact/components/splitbutton/SplitButtonItem' {
  declare module.exports: any;
}

declare module 'primereact/components/splitbutton/SplitButtonPanel' {
  declare module.exports: any;
}

declare module 'primereact/components/steps/Steps' {
  declare module.exports: any;
}

declare module 'primereact/components/tabmenu/TabMenu' {
  declare module.exports: any;
}

declare module 'primereact/components/tabview/TabView' {
  declare module.exports: any;
}

declare module 'primereact/components/tieredmenu/TieredMenu' {
  declare module.exports: any;
}

declare module 'primereact/components/togglebutton/ToggleButton' {
  declare module.exports: any;
}

declare module 'primereact/components/toolbar/Toolbar' {
  declare module.exports: any;
}

declare module 'primereact/components/tooltip/Tooltip' {
  declare module.exports: any;
}

declare module 'primereact/components/tree/Tree' {
  declare module.exports: any;
}

declare module 'primereact/components/treetable/TreeTable' {
  declare module.exports: any;
}

declare module 'primereact/components/treetable/TreeTableFooter' {
  declare module.exports: any;
}

declare module 'primereact/components/treetable/TreeTableFooterCell' {
  declare module.exports: any;
}

declare module 'primereact/components/treetable/TreeTableHeader' {
  declare module.exports: any;
}

declare module 'primereact/components/treetable/TreeTableHeaderCell' {
  declare module.exports: any;
}

declare module 'primereact/components/treetable/UITreeRow' {
  declare module.exports: any;
}

declare module 'primereact/components/tristatecheckbox/TriStateCheckbox' {
  declare module.exports: any;
}

declare module 'primereact/components/utils/DomHandler' {
  declare module.exports: any;
}

declare module 'primereact/components/utils/ObjectUtils' {
  declare module.exports: any;
}

declare module 'primereact/components/utils/UniqueComponentId' {
  declare module.exports: any;
}

// Filename aliases
declare module 'primereact/components/accordion/Accordion.js' {
  declare module.exports: $Exports<'primereact/components/accordion/Accordion'>;
}
declare module 'primereact/components/autocomplete/AutoComplete.js' {
  declare module.exports: $Exports<'primereact/components/autocomplete/AutoComplete'>;
}
declare module 'primereact/components/autocomplete/AutoCompletePanel.js' {
  declare module.exports: $Exports<'primereact/components/autocomplete/AutoCompletePanel'>;
}
declare module 'primereact/components/breadcrumb/BreadCrumb.js' {
  declare module.exports: $Exports<'primereact/components/breadcrumb/BreadCrumb'>;
}
declare module 'primereact/components/button/Button.js' {
  declare module.exports: $Exports<'primereact/components/button/Button'>;
}
declare module 'primereact/components/calendar/Calendar.js' {
  declare module.exports: $Exports<'primereact/components/calendar/Calendar'>;
}
declare module 'primereact/components/calendar/CalendarPanel.js' {
  declare module.exports: $Exports<'primereact/components/calendar/CalendarPanel'>;
}
declare module 'primereact/components/captcha/Captcha.js' {
  declare module.exports: $Exports<'primereact/components/captcha/Captcha'>;
}
declare module 'primereact/components/card/Card.js' {
  declare module.exports: $Exports<'primereact/components/card/Card'>;
}
declare module 'primereact/components/chart/Chart.js' {
  declare module.exports: $Exports<'primereact/components/chart/Chart'>;
}
declare module 'primereact/components/checkbox/Checkbox.js' {
  declare module.exports: $Exports<'primereact/components/checkbox/Checkbox'>;
}
declare module 'primereact/components/chips/Chips.js' {
  declare module.exports: $Exports<'primereact/components/chips/Chips'>;
}
declare module 'primereact/components/colorpicker/ColorPicker.js' {
  declare module.exports: $Exports<'primereact/components/colorpicker/ColorPicker'>;
}
declare module 'primereact/components/colorpicker/ColorPickerPanel.js' {
  declare module.exports: $Exports<'primereact/components/colorpicker/ColorPickerPanel'>;
}
declare module 'primereact/components/column/Column.js' {
  declare module.exports: $Exports<'primereact/components/column/Column'>;
}
declare module 'primereact/components/columngroup/ColumnGroup.js' {
  declare module.exports: $Exports<'primereact/components/columngroup/ColumnGroup'>;
}
declare module 'primereact/components/contextmenu/ContextMenu.js' {
  declare module.exports: $Exports<'primereact/components/contextmenu/ContextMenu'>;
}
declare module 'primereact/components/datagrid/DataGrid.js' {
  declare module.exports: $Exports<'primereact/components/datagrid/DataGrid'>;
}
declare module 'primereact/components/datalist/DataList.js' {
  declare module.exports: $Exports<'primereact/components/datalist/DataList'>;
}
declare module 'primereact/components/datascroller/DataScroller.js' {
  declare module.exports: $Exports<'primereact/components/datascroller/DataScroller'>;
}
declare module 'primereact/components/datatable/BodyCell.js' {
  declare module.exports: $Exports<'primereact/components/datatable/BodyCell'>;
}
declare module 'primereact/components/datatable/BodyRow.js' {
  declare module.exports: $Exports<'primereact/components/datatable/BodyRow'>;
}
declare module 'primereact/components/datatable/DataTable.js' {
  declare module.exports: $Exports<'primereact/components/datatable/DataTable'>;
}
declare module 'primereact/components/datatable/FooterCell.js' {
  declare module.exports: $Exports<'primereact/components/datatable/FooterCell'>;
}
declare module 'primereact/components/datatable/HeaderCell.js' {
  declare module.exports: $Exports<'primereact/components/datatable/HeaderCell'>;
}
declare module 'primereact/components/datatable/RowCheckbox.js' {
  declare module.exports: $Exports<'primereact/components/datatable/RowCheckbox'>;
}
declare module 'primereact/components/datatable/RowRadioButton.js' {
  declare module.exports: $Exports<'primereact/components/datatable/RowRadioButton'>;
}
declare module 'primereact/components/datatable/ScrollableView.js' {
  declare module.exports: $Exports<'primereact/components/datatable/ScrollableView'>;
}
declare module 'primereact/components/datatable/TableBody.js' {
  declare module.exports: $Exports<'primereact/components/datatable/TableBody'>;
}
declare module 'primereact/components/datatable/TableFooter.js' {
  declare module.exports: $Exports<'primereact/components/datatable/TableFooter'>;
}
declare module 'primereact/components/datatable/TableHeader.js' {
  declare module.exports: $Exports<'primereact/components/datatable/TableHeader'>;
}
declare module 'primereact/components/dataview/DataView.js' {
  declare module.exports: $Exports<'primereact/components/dataview/DataView'>;
}
declare module 'primereact/components/dialog/Dialog.js' {
  declare module.exports: $Exports<'primereact/components/dialog/Dialog'>;
}
declare module 'primereact/components/dropdown/Dropdown.js' {
  declare module.exports: $Exports<'primereact/components/dropdown/Dropdown'>;
}
declare module 'primereact/components/dropdown/DropdownItem.js' {
  declare module.exports: $Exports<'primereact/components/dropdown/DropdownItem'>;
}
declare module 'primereact/components/dropdown/DropdownPanel.js' {
  declare module.exports: $Exports<'primereact/components/dropdown/DropdownPanel'>;
}
declare module 'primereact/components/editor/Editor.js' {
  declare module.exports: $Exports<'primereact/components/editor/Editor'>;
}
declare module 'primereact/components/fieldset/Fieldset.js' {
  declare module.exports: $Exports<'primereact/components/fieldset/Fieldset'>;
}
declare module 'primereact/components/fileupload/FileUpload.js' {
  declare module.exports: $Exports<'primereact/components/fileupload/FileUpload'>;
}
declare module 'primereact/components/gmap/GMap.js' {
  declare module.exports: $Exports<'primereact/components/gmap/GMap'>;
}
declare module 'primereact/components/growl/Growl.js' {
  declare module.exports: $Exports<'primereact/components/growl/Growl'>;
}
declare module 'primereact/components/growl/GrowlMessage.js' {
  declare module.exports: $Exports<'primereact/components/growl/GrowlMessage'>;
}
declare module 'primereact/components/inputmask/InputMask.js' {
  declare module.exports: $Exports<'primereact/components/inputmask/InputMask'>;
}
declare module 'primereact/components/inputswitch/InputSwitch.js' {
  declare module.exports: $Exports<'primereact/components/inputswitch/InputSwitch'>;
}
declare module 'primereact/components/inputtext/InputText.js' {
  declare module.exports: $Exports<'primereact/components/inputtext/InputText'>;
}
declare module 'primereact/components/inputtextarea/InputTextarea.js' {
  declare module.exports: $Exports<'primereact/components/inputtextarea/InputTextarea'>;
}
declare module 'primereact/components/keyfilter/KeyFilter.js' {
  declare module.exports: $Exports<'primereact/components/keyfilter/KeyFilter'>;
}
declare module 'primereact/components/lightbox/Lightbox.js' {
  declare module.exports: $Exports<'primereact/components/lightbox/Lightbox'>;
}
declare module 'primereact/components/listbox/ListBox.js' {
  declare module.exports: $Exports<'primereact/components/listbox/ListBox'>;
}
declare module 'primereact/components/listbox/ListBoxHeader.js' {
  declare module.exports: $Exports<'primereact/components/listbox/ListBoxHeader'>;
}
declare module 'primereact/components/listbox/ListBoxItem.js' {
  declare module.exports: $Exports<'primereact/components/listbox/ListBoxItem'>;
}
declare module 'primereact/components/megamenu/MegaMenu.js' {
  declare module.exports: $Exports<'primereact/components/megamenu/MegaMenu'>;
}
declare module 'primereact/components/menu/Menu.js' {
  declare module.exports: $Exports<'primereact/components/menu/Menu'>;
}
declare module 'primereact/components/menu/MenuItem.js' {
  declare module.exports: $Exports<'primereact/components/menu/MenuItem'>;
}
declare module 'primereact/components/menubar/Menubar.js' {
  declare module.exports: $Exports<'primereact/components/menubar/Menubar'>;
}
declare module 'primereact/components/message/Message.js' {
  declare module.exports: $Exports<'primereact/components/message/Message'>;
}
declare module 'primereact/components/messages/Messages.js' {
  declare module.exports: $Exports<'primereact/components/messages/Messages'>;
}
declare module 'primereact/components/messages/UIMessage.js' {
  declare module.exports: $Exports<'primereact/components/messages/UIMessage'>;
}
declare module 'primereact/components/multiselect/MultiSelect.js' {
  declare module.exports: $Exports<'primereact/components/multiselect/MultiSelect'>;
}
declare module 'primereact/components/multiselect/MultiSelectHeader.js' {
  declare module.exports: $Exports<'primereact/components/multiselect/MultiSelectHeader'>;
}
declare module 'primereact/components/multiselect/MultiSelectItem.js' {
  declare module.exports: $Exports<'primereact/components/multiselect/MultiSelectItem'>;
}
declare module 'primereact/components/multiselect/MultiSelectPanel.js' {
  declare module.exports: $Exports<'primereact/components/multiselect/MultiSelectPanel'>;
}
declare module 'primereact/components/nestedmenu/NestedMenu.js' {
  declare module.exports: $Exports<'primereact/components/nestedmenu/NestedMenu'>;
}
declare module 'primereact/components/nestedmenu/NestedMenuItem.js' {
  declare module.exports: $Exports<'primereact/components/nestedmenu/NestedMenuItem'>;
}
declare module 'primereact/components/orderlist/OrderList.js' {
  declare module.exports: $Exports<'primereact/components/orderlist/OrderList'>;
}
declare module 'primereact/components/orderlist/OrderListControls.js' {
  declare module.exports: $Exports<'primereact/components/orderlist/OrderListControls'>;
}
declare module 'primereact/components/orderlist/OrderListSubList.js' {
  declare module.exports: $Exports<'primereact/components/orderlist/OrderListSubList'>;
}
declare module 'primereact/components/organizationchart/OrganizationChart.js' {
  declare module.exports: $Exports<'primereact/components/organizationchart/OrganizationChart'>;
}
declare module 'primereact/components/overlaypanel/OverlayPanel.js' {
  declare module.exports: $Exports<'primereact/components/overlaypanel/OverlayPanel'>;
}
declare module 'primereact/components/paginator/CurrentPageReport.js' {
  declare module.exports: $Exports<'primereact/components/paginator/CurrentPageReport'>;
}
declare module 'primereact/components/paginator/FirstPageLink.js' {
  declare module.exports: $Exports<'primereact/components/paginator/FirstPageLink'>;
}
declare module 'primereact/components/paginator/LastPageLink.js' {
  declare module.exports: $Exports<'primereact/components/paginator/LastPageLink'>;
}
declare module 'primereact/components/paginator/NextPageLink.js' {
  declare module.exports: $Exports<'primereact/components/paginator/NextPageLink'>;
}
declare module 'primereact/components/paginator/PageLinks.js' {
  declare module.exports: $Exports<'primereact/components/paginator/PageLinks'>;
}
declare module 'primereact/components/paginator/Paginator.js' {
  declare module.exports: $Exports<'primereact/components/paginator/Paginator'>;
}
declare module 'primereact/components/paginator/PrevPageLink.js' {
  declare module.exports: $Exports<'primereact/components/paginator/PrevPageLink'>;
}
declare module 'primereact/components/paginator/RowsPerPageDropdown.js' {
  declare module.exports: $Exports<'primereact/components/paginator/RowsPerPageDropdown'>;
}
declare module 'primereact/components/panel/Panel.js' {
  declare module.exports: $Exports<'primereact/components/panel/Panel'>;
}
declare module 'primereact/components/panelmenu/PanelMenu.js' {
  declare module.exports: $Exports<'primereact/components/panelmenu/PanelMenu'>;
}
declare module 'primereact/components/password/Password.js' {
  declare module.exports: $Exports<'primereact/components/password/Password'>;
}
declare module 'primereact/components/picklist/PickList.js' {
  declare module.exports: $Exports<'primereact/components/picklist/PickList'>;
}
declare module 'primereact/components/picklist/PickListControls.js' {
  declare module.exports: $Exports<'primereact/components/picklist/PickListControls'>;
}
declare module 'primereact/components/picklist/PickListItem.js' {
  declare module.exports: $Exports<'primereact/components/picklist/PickListItem'>;
}
declare module 'primereact/components/picklist/PickListSubList.js' {
  declare module.exports: $Exports<'primereact/components/picklist/PickListSubList'>;
}
declare module 'primereact/components/picklist/PickListTransferControls.js' {
  declare module.exports: $Exports<'primereact/components/picklist/PickListTransferControls'>;
}
declare module 'primereact/components/progressbar/ProgressBar.js' {
  declare module.exports: $Exports<'primereact/components/progressbar/ProgressBar'>;
}
declare module 'primereact/components/progressspinner/ProgressSpinner.js' {
  declare module.exports: $Exports<'primereact/components/progressspinner/ProgressSpinner'>;
}
declare module 'primereact/components/radiobutton/RadioButton.js' {
  declare module.exports: $Exports<'primereact/components/radiobutton/RadioButton'>;
}
declare module 'primereact/components/rating/Rating.js' {
  declare module.exports: $Exports<'primereact/components/rating/Rating'>;
}
declare module 'primereact/components/row/Row.js' {
  declare module.exports: $Exports<'primereact/components/row/Row'>;
}
declare module 'primereact/components/schedule/Schedule.js' {
  declare module.exports: $Exports<'primereact/components/schedule/Schedule'>;
}
declare module 'primereact/components/scrollpanel/ScrollPanel.js' {
  declare module.exports: $Exports<'primereact/components/scrollpanel/ScrollPanel'>;
}
declare module 'primereact/components/selectbutton/SelectButton.js' {
  declare module.exports: $Exports<'primereact/components/selectbutton/SelectButton'>;
}
declare module 'primereact/components/selectbutton/SelectButtonItem.js' {
  declare module.exports: $Exports<'primereact/components/selectbutton/SelectButtonItem'>;
}
declare module 'primereact/components/sidebar/Sidebar.js' {
  declare module.exports: $Exports<'primereact/components/sidebar/Sidebar'>;
}
declare module 'primereact/components/slidemenu/SlideMenu.js' {
  declare module.exports: $Exports<'primereact/components/slidemenu/SlideMenu'>;
}
declare module 'primereact/components/slider/Slider.js' {
  declare module.exports: $Exports<'primereact/components/slider/Slider'>;
}
declare module 'primereact/components/spinner/Spinner.js' {
  declare module.exports: $Exports<'primereact/components/spinner/Spinner'>;
}
declare module 'primereact/components/splitbutton/SplitButton.js' {
  declare module.exports: $Exports<'primereact/components/splitbutton/SplitButton'>;
}
declare module 'primereact/components/splitbutton/SplitButtonItem.js' {
  declare module.exports: $Exports<'primereact/components/splitbutton/SplitButtonItem'>;
}
declare module 'primereact/components/splitbutton/SplitButtonPanel.js' {
  declare module.exports: $Exports<'primereact/components/splitbutton/SplitButtonPanel'>;
}
declare module 'primereact/components/steps/Steps.js' {
  declare module.exports: $Exports<'primereact/components/steps/Steps'>;
}
declare module 'primereact/components/tabmenu/TabMenu.js' {
  declare module.exports: $Exports<'primereact/components/tabmenu/TabMenu'>;
}
declare module 'primereact/components/tabview/TabView.js' {
  declare module.exports: $Exports<'primereact/components/tabview/TabView'>;
}
declare module 'primereact/components/tieredmenu/TieredMenu.js' {
  declare module.exports: $Exports<'primereact/components/tieredmenu/TieredMenu'>;
}
declare module 'primereact/components/togglebutton/ToggleButton.js' {
  declare module.exports: $Exports<'primereact/components/togglebutton/ToggleButton'>;
}
declare module 'primereact/components/toolbar/Toolbar.js' {
  declare module.exports: $Exports<'primereact/components/toolbar/Toolbar'>;
}
declare module 'primereact/components/tooltip/Tooltip.js' {
  declare module.exports: $Exports<'primereact/components/tooltip/Tooltip'>;
}
declare module 'primereact/components/tree/Tree.js' {
  declare module.exports: $Exports<'primereact/components/tree/Tree'>;
}
declare module 'primereact/components/treetable/TreeTable.js' {
  declare module.exports: $Exports<'primereact/components/treetable/TreeTable'>;
}
declare module 'primereact/components/treetable/TreeTableFooter.js' {
  declare module.exports: $Exports<'primereact/components/treetable/TreeTableFooter'>;
}
declare module 'primereact/components/treetable/TreeTableFooterCell.js' {
  declare module.exports: $Exports<'primereact/components/treetable/TreeTableFooterCell'>;
}
declare module 'primereact/components/treetable/TreeTableHeader.js' {
  declare module.exports: $Exports<'primereact/components/treetable/TreeTableHeader'>;
}
declare module 'primereact/components/treetable/TreeTableHeaderCell.js' {
  declare module.exports: $Exports<'primereact/components/treetable/TreeTableHeaderCell'>;
}
declare module 'primereact/components/treetable/UITreeRow.js' {
  declare module.exports: $Exports<'primereact/components/treetable/UITreeRow'>;
}
declare module 'primereact/components/tristatecheckbox/TriStateCheckbox.js' {
  declare module.exports: $Exports<'primereact/components/tristatecheckbox/TriStateCheckbox'>;
}
declare module 'primereact/components/utils/DomHandler.js' {
  declare module.exports: $Exports<'primereact/components/utils/DomHandler'>;
}
declare module 'primereact/components/utils/ObjectUtils.js' {
  declare module.exports: $Exports<'primereact/components/utils/ObjectUtils'>;
}
declare module 'primereact/components/utils/UniqueComponentId.js' {
  declare module.exports: $Exports<'primereact/components/utils/UniqueComponentId'>;
}
