// flow-typed signature: 3e70d807d3a536b68620d89c254a46d0
// flow-typed version: <<STUB>>/react-trello_v^1.33.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-trello'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-trello' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-trello/dist/actions/BoardActions' {
  declare module.exports: any;
}

declare module 'react-trello/dist/actions/LaneActions' {
  declare module.exports: any;
}

declare module 'react-trello/dist/components/Board' {
  declare module.exports: any;
}

declare module 'react-trello/dist/components/BoardContainer' {
  declare module.exports: any;
}

declare module 'react-trello/dist/components/Card' {
  declare module.exports: any;
}

declare module 'react-trello/dist/components/Lane' {
  declare module.exports: any;
}

declare module 'react-trello/dist/components/Loader' {
  declare module.exports: any;
}

declare module 'react-trello/dist/components/NewCard' {
  declare module.exports: any;
}

declare module 'react-trello/dist/components/Tag' {
  declare module.exports: any;
}

declare module 'react-trello/dist/components/widgets/DeleteButton' {
  declare module.exports: any;
}

declare module 'react-trello/dist/components/widgets/EditableLabel' {
  declare module.exports: any;
}

declare module 'react-trello/dist/dnd/Container' {
  declare module.exports: any;
}

declare module 'react-trello/dist/dnd/Draggable' {
  declare module.exports: any;
}

declare module 'react-trello/dist/helpers/DragType' {
  declare module.exports: any;
}

declare module 'react-trello/dist/helpers/LaneHelper' {
  declare module.exports: any;
}

declare module 'react-trello/dist/index' {
  declare module.exports: any;
}

declare module 'react-trello/dist/reducers/BoardReducer' {
  declare module.exports: any;
}

declare module 'react-trello/dist/styles/Base' {
  declare module.exports: any;
}

declare module 'react-trello/dist/styles/Elements' {
  declare module.exports: any;
}

declare module 'react-trello/dist/styles/Loader' {
  declare module.exports: any;
}

declare module 'react-trello/src/actions/BoardActions' {
  declare module.exports: any;
}

declare module 'react-trello/src/actions/LaneActions' {
  declare module.exports: any;
}

declare module 'react-trello/src/components/Board' {
  declare module.exports: any;
}

declare module 'react-trello/src/components/BoardContainer' {
  declare module.exports: any;
}

declare module 'react-trello/src/components/Card' {
  declare module.exports: any;
}

declare module 'react-trello/src/components/Lane' {
  declare module.exports: any;
}

declare module 'react-trello/src/components/Loader' {
  declare module.exports: any;
}

declare module 'react-trello/src/components/NewCard' {
  declare module.exports: any;
}

declare module 'react-trello/src/components/Tag' {
  declare module.exports: any;
}

declare module 'react-trello/src/components/widgets/DeleteButton' {
  declare module.exports: any;
}

declare module 'react-trello/src/components/widgets/EditableLabel' {
  declare module.exports: any;
}

declare module 'react-trello/src/dnd/Container' {
  declare module.exports: any;
}

declare module 'react-trello/src/dnd/Draggable' {
  declare module.exports: any;
}

declare module 'react-trello/src/helpers/LaneHelper' {
  declare module.exports: any;
}

declare module 'react-trello/src/index' {
  declare module.exports: any;
}

declare module 'react-trello/src/reducers/BoardReducer' {
  declare module.exports: any;
}

declare module 'react-trello/src/styles/Base' {
  declare module.exports: any;
}

declare module 'react-trello/src/styles/Elements' {
  declare module.exports: any;
}

declare module 'react-trello/src/styles/Loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-trello/dist/actions/BoardActions.js' {
  declare module.exports: $Exports<'react-trello/dist/actions/BoardActions'>;
}
declare module 'react-trello/dist/actions/LaneActions.js' {
  declare module.exports: $Exports<'react-trello/dist/actions/LaneActions'>;
}
declare module 'react-trello/dist/components/Board.js' {
  declare module.exports: $Exports<'react-trello/dist/components/Board'>;
}
declare module 'react-trello/dist/components/BoardContainer.js' {
  declare module.exports: $Exports<'react-trello/dist/components/BoardContainer'>;
}
declare module 'react-trello/dist/components/Card.js' {
  declare module.exports: $Exports<'react-trello/dist/components/Card'>;
}
declare module 'react-trello/dist/components/Lane.js' {
  declare module.exports: $Exports<'react-trello/dist/components/Lane'>;
}
declare module 'react-trello/dist/components/Loader.js' {
  declare module.exports: $Exports<'react-trello/dist/components/Loader'>;
}
declare module 'react-trello/dist/components/NewCard.js' {
  declare module.exports: $Exports<'react-trello/dist/components/NewCard'>;
}
declare module 'react-trello/dist/components/Tag.js' {
  declare module.exports: $Exports<'react-trello/dist/components/Tag'>;
}
declare module 'react-trello/dist/components/widgets/DeleteButton.js' {
  declare module.exports: $Exports<'react-trello/dist/components/widgets/DeleteButton'>;
}
declare module 'react-trello/dist/components/widgets/EditableLabel.js' {
  declare module.exports: $Exports<'react-trello/dist/components/widgets/EditableLabel'>;
}
declare module 'react-trello/dist/dnd/Container.js' {
  declare module.exports: $Exports<'react-trello/dist/dnd/Container'>;
}
declare module 'react-trello/dist/dnd/Draggable.js' {
  declare module.exports: $Exports<'react-trello/dist/dnd/Draggable'>;
}
declare module 'react-trello/dist/helpers/DragType.js' {
  declare module.exports: $Exports<'react-trello/dist/helpers/DragType'>;
}
declare module 'react-trello/dist/helpers/LaneHelper.js' {
  declare module.exports: $Exports<'react-trello/dist/helpers/LaneHelper'>;
}
declare module 'react-trello/dist/index.js' {
  declare module.exports: $Exports<'react-trello/dist/index'>;
}
declare module 'react-trello/dist/reducers/BoardReducer.js' {
  declare module.exports: $Exports<'react-trello/dist/reducers/BoardReducer'>;
}
declare module 'react-trello/dist/styles/Base.js' {
  declare module.exports: $Exports<'react-trello/dist/styles/Base'>;
}
declare module 'react-trello/dist/styles/Elements.js' {
  declare module.exports: $Exports<'react-trello/dist/styles/Elements'>;
}
declare module 'react-trello/dist/styles/Loader.js' {
  declare module.exports: $Exports<'react-trello/dist/styles/Loader'>;
}
declare module 'react-trello/src/actions/BoardActions.js' {
  declare module.exports: $Exports<'react-trello/src/actions/BoardActions'>;
}
declare module 'react-trello/src/actions/LaneActions.js' {
  declare module.exports: $Exports<'react-trello/src/actions/LaneActions'>;
}
declare module 'react-trello/src/components/Board.js' {
  declare module.exports: $Exports<'react-trello/src/components/Board'>;
}
declare module 'react-trello/src/components/BoardContainer.js' {
  declare module.exports: $Exports<'react-trello/src/components/BoardContainer'>;
}
declare module 'react-trello/src/components/Card.js' {
  declare module.exports: $Exports<'react-trello/src/components/Card'>;
}
declare module 'react-trello/src/components/Lane.js' {
  declare module.exports: $Exports<'react-trello/src/components/Lane'>;
}
declare module 'react-trello/src/components/Loader.js' {
  declare module.exports: $Exports<'react-trello/src/components/Loader'>;
}
declare module 'react-trello/src/components/NewCard.js' {
  declare module.exports: $Exports<'react-trello/src/components/NewCard'>;
}
declare module 'react-trello/src/components/Tag.js' {
  declare module.exports: $Exports<'react-trello/src/components/Tag'>;
}
declare module 'react-trello/src/components/widgets/DeleteButton.js' {
  declare module.exports: $Exports<'react-trello/src/components/widgets/DeleteButton'>;
}
declare module 'react-trello/src/components/widgets/EditableLabel.js' {
  declare module.exports: $Exports<'react-trello/src/components/widgets/EditableLabel'>;
}
declare module 'react-trello/src/dnd/Container.js' {
  declare module.exports: $Exports<'react-trello/src/dnd/Container'>;
}
declare module 'react-trello/src/dnd/Draggable.js' {
  declare module.exports: $Exports<'react-trello/src/dnd/Draggable'>;
}
declare module 'react-trello/src/helpers/LaneHelper.js' {
  declare module.exports: $Exports<'react-trello/src/helpers/LaneHelper'>;
}
declare module 'react-trello/src/index.js' {
  declare module.exports: $Exports<'react-trello/src/index'>;
}
declare module 'react-trello/src/reducers/BoardReducer.js' {
  declare module.exports: $Exports<'react-trello/src/reducers/BoardReducer'>;
}
declare module 'react-trello/src/styles/Base.js' {
  declare module.exports: $Exports<'react-trello/src/styles/Base'>;
}
declare module 'react-trello/src/styles/Elements.js' {
  declare module.exports: $Exports<'react-trello/src/styles/Elements'>;
}
declare module 'react-trello/src/styles/Loader.js' {
  declare module.exports: $Exports<'react-trello/src/styles/Loader'>;
}
