// flow-typed signature: 8244645e5eec9b915efb6f8c32fdbc2d
// flow-typed version: <<STUB>>/react-leaflet-measure_v^0.1.2/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-leaflet-measure'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-leaflet-measure' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-leaflet-measure/dist/react-leaflet-measure' {
  declare module.exports: any;
}

declare module 'react-leaflet-measure/dist/react-leaflet-measure.min' {
  declare module.exports: any;
}

declare module 'react-leaflet-measure/lib/index' {
  declare module.exports: any;
}

declare module 'react-leaflet-measure/lib/MeasureControl' {
  declare module.exports: any;
}

declare module 'react-leaflet-measure/src/index' {
  declare module.exports: any;
}

declare module 'react-leaflet-measure/src/MeasureControl' {
  declare module.exports: any;
}

declare module 'react-leaflet-measure/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-leaflet-measure/dist/react-leaflet-measure.js' {
  declare module.exports: $Exports<'react-leaflet-measure/dist/react-leaflet-measure'>;
}
declare module 'react-leaflet-measure/dist/react-leaflet-measure.min.js' {
  declare module.exports: $Exports<'react-leaflet-measure/dist/react-leaflet-measure.min'>;
}
declare module 'react-leaflet-measure/lib/index.js' {
  declare module.exports: $Exports<'react-leaflet-measure/lib/index'>;
}
declare module 'react-leaflet-measure/lib/MeasureControl.js' {
  declare module.exports: $Exports<'react-leaflet-measure/lib/MeasureControl'>;
}
declare module 'react-leaflet-measure/src/index.js' {
  declare module.exports: $Exports<'react-leaflet-measure/src/index'>;
}
declare module 'react-leaflet-measure/src/MeasureControl.js' {
  declare module.exports: $Exports<'react-leaflet-measure/src/MeasureControl'>;
}
declare module 'react-leaflet-measure/webpack.config.js' {
  declare module.exports: $Exports<'react-leaflet-measure/webpack.config'>;
}
