// flow-typed signature: 600a17c6a70778430d0272c5a7985b72
// flow-typed version: <<STUB>>/react-geolocated_v^2.3.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-geolocated'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-geolocated' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-geolocated/dist-modules/components/geolocated' {
  declare module.exports: any;
}

declare module 'react-geolocated/dist-modules/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-geolocated/dist-modules/components/geolocated.js' {
  declare module.exports: $Exports<'react-geolocated/dist-modules/components/geolocated'>;
}
declare module 'react-geolocated/dist-modules/index.js' {
  declare module.exports: $Exports<'react-geolocated/dist-modules/index'>;
}
