// flow-typed signature: dc63104772a5789e4c16ebfaa8c4a80b
// flow-typed version: <<STUB>>/react-leaflet-markercluster_v^1.1.8/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-leaflet-markercluster'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-leaflet-markercluster' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-leaflet-markercluster/dist/react-leaflet-markercluster' {
  declare module.exports: any;
}

declare module 'react-leaflet-markercluster/dist/react-leaflet-markercluster.min' {
  declare module.exports: any;
}

declare module 'react-leaflet-markercluster/src/react-leaflet-markercluster' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-leaflet-markercluster/dist/react-leaflet-markercluster.js' {
  declare module.exports: $Exports<'react-leaflet-markercluster/dist/react-leaflet-markercluster'>;
}
declare module 'react-leaflet-markercluster/dist/react-leaflet-markercluster.min.js' {
  declare module.exports: $Exports<'react-leaflet-markercluster/dist/react-leaflet-markercluster.min'>;
}
declare module 'react-leaflet-markercluster/src/react-leaflet-markercluster.js' {
  declare module.exports: $Exports<'react-leaflet-markercluster/src/react-leaflet-markercluster'>;
}
