// flow-typed signature: 132c25170ff5fee2440533c54f00edcf
// flow-typed version: <<STUB>>/react-leaflet-div-icon_v^1.1.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-leaflet-div-icon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-leaflet-div-icon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-leaflet-div-icon/div-icon' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-leaflet-div-icon/div-icon.js' {
  declare module.exports: $Exports<'react-leaflet-div-icon/div-icon'>;
}
declare module 'react-leaflet-div-icon/index' {
  declare module.exports: $Exports<'react-leaflet-div-icon'>;
}
declare module 'react-leaflet-div-icon/index.js' {
  declare module.exports: $Exports<'react-leaflet-div-icon'>;
}
