// flow-typed signature: 84787b1935b7377992d52563c679daa3
// flow-typed version: <<STUB>>/react-tiny-virtual-list_v^2.2.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-tiny-virtual-list'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-tiny-virtual-list' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-tiny-virtual-list/build/react-tiny-virtual-list.cjs' {
  declare module.exports: any;
}

declare module 'react-tiny-virtual-list/build/react-tiny-virtual-list.es' {
  declare module.exports: any;
}

declare module 'react-tiny-virtual-list/build/react-tiny-virtual-list' {
  declare module.exports: any;
}

declare module 'react-tiny-virtual-list/build/react-tiny-virtual-list.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-tiny-virtual-list/build/react-tiny-virtual-list.cjs.js' {
  declare module.exports: $Exports<'react-tiny-virtual-list/build/react-tiny-virtual-list.cjs'>;
}
declare module 'react-tiny-virtual-list/build/react-tiny-virtual-list.es.js' {
  declare module.exports: $Exports<'react-tiny-virtual-list/build/react-tiny-virtual-list.es'>;
}
declare module 'react-tiny-virtual-list/build/react-tiny-virtual-list.js' {
  declare module.exports: $Exports<'react-tiny-virtual-list/build/react-tiny-virtual-list'>;
}
declare module 'react-tiny-virtual-list/build/react-tiny-virtual-list.min.js' {
  declare module.exports: $Exports<'react-tiny-virtual-list/build/react-tiny-virtual-list.min'>;
}
