// flow-typed signature: 368b29b5fa98d13dd636f0da8bbec108
// flow-typed version: <<STUB>>/react-avatar-editor_v^11.0.2/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-avatar-editor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-avatar-editor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-avatar-editor/dist/index' {
  declare module.exports: any;
}

declare module 'react-avatar-editor/src/index' {
  declare module.exports: any;
}

declare module 'react-avatar-editor/src/utils/load-image-file' {
  declare module.exports: any;
}

declare module 'react-avatar-editor/src/utils/load-image-url' {
  declare module.exports: any;
}

declare module 'react-avatar-editor/src/utils/parse-dom' {
  declare module.exports: any;
}

declare module 'react-avatar-editor/src/utils/parse-dom.test' {
  declare module.exports: any;
}

declare module 'react-avatar-editor/src/utils/retrieve-image-url' {
  declare module.exports: any;
}

declare module 'react-avatar-editor/src/utils/retrieve-image-url.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-avatar-editor/dist/index.js' {
  declare module.exports: $Exports<'react-avatar-editor/dist/index'>;
}
declare module 'react-avatar-editor/src/index.js' {
  declare module.exports: $Exports<'react-avatar-editor/src/index'>;
}
declare module 'react-avatar-editor/src/utils/load-image-file.js' {
  declare module.exports: $Exports<'react-avatar-editor/src/utils/load-image-file'>;
}
declare module 'react-avatar-editor/src/utils/load-image-url.js' {
  declare module.exports: $Exports<'react-avatar-editor/src/utils/load-image-url'>;
}
declare module 'react-avatar-editor/src/utils/parse-dom.js' {
  declare module.exports: $Exports<'react-avatar-editor/src/utils/parse-dom'>;
}
declare module 'react-avatar-editor/src/utils/parse-dom.test.js' {
  declare module.exports: $Exports<'react-avatar-editor/src/utils/parse-dom.test'>;
}
declare module 'react-avatar-editor/src/utils/retrieve-image-url.js' {
  declare module.exports: $Exports<'react-avatar-editor/src/utils/retrieve-image-url'>;
}
declare module 'react-avatar-editor/src/utils/retrieve-image-url.test.js' {
  declare module.exports: $Exports<'react-avatar-editor/src/utils/retrieve-image-url.test'>;
}
