// flow-typed signature: 0f702e1ec144b6e16957f554bdeba25a
// flow-typed version: <<STUB>>/react-alice-carousel_v^1.13.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-alice-carousel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-alice-carousel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-alice-carousel/lib/prop-types' {
  declare module.exports: any;
}

declare module 'react-alice-carousel/lib/react-alice-carousel' {
  declare module.exports: any;
}

declare module 'react-alice-carousel/lib/utils/animation' {
  declare module.exports: any;
}

declare module 'react-alice-carousel/lib/utils/classnames' {
  declare module.exports: any;
}

declare module 'react-alice-carousel/lib/utils/common' {
  declare module.exports: any;
}

declare module 'react-alice-carousel/lib/utils/debug' {
  declare module.exports: any;
}

declare module 'react-alice-carousel/lib/utils/device' {
  declare module.exports: any;
}

declare module 'react-alice-carousel/lib/utils/elements' {
  declare module.exports: any;
}

declare module 'react-alice-carousel/lib/utils/index' {
  declare module.exports: any;
}

declare module 'react-alice-carousel/lib/utils/math' {
  declare module.exports: any;
}

declare module 'react-alice-carousel/lib/utils/style' {
  declare module.exports: any;
}

declare module 'react-alice-carousel/lib/utils/swipe' {
  declare module.exports: any;
}

declare module 'react-alice-carousel/lib/utils/timers' {
  declare module.exports: any;
}

declare module 'react-alice-carousel/lib/views/DotsNavigation' {
  declare module.exports: any;
}

declare module 'react-alice-carousel/lib/views/index' {
  declare module.exports: any;
}

declare module 'react-alice-carousel/lib/views/PlayPauseButton' {
  declare module.exports: any;
}

declare module 'react-alice-carousel/lib/views/PrevNextButton' {
  declare module.exports: any;
}

declare module 'react-alice-carousel/lib/views/SlideInfo' {
  declare module.exports: any;
}

declare module 'react-alice-carousel/lib/views/StageItem' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-alice-carousel/lib/prop-types.js' {
  declare module.exports: $Exports<'react-alice-carousel/lib/prop-types'>;
}
declare module 'react-alice-carousel/lib/react-alice-carousel.js' {
  declare module.exports: $Exports<'react-alice-carousel/lib/react-alice-carousel'>;
}
declare module 'react-alice-carousel/lib/utils/animation.js' {
  declare module.exports: $Exports<'react-alice-carousel/lib/utils/animation'>;
}
declare module 'react-alice-carousel/lib/utils/classnames.js' {
  declare module.exports: $Exports<'react-alice-carousel/lib/utils/classnames'>;
}
declare module 'react-alice-carousel/lib/utils/common.js' {
  declare module.exports: $Exports<'react-alice-carousel/lib/utils/common'>;
}
declare module 'react-alice-carousel/lib/utils/debug.js' {
  declare module.exports: $Exports<'react-alice-carousel/lib/utils/debug'>;
}
declare module 'react-alice-carousel/lib/utils/device.js' {
  declare module.exports: $Exports<'react-alice-carousel/lib/utils/device'>;
}
declare module 'react-alice-carousel/lib/utils/elements.js' {
  declare module.exports: $Exports<'react-alice-carousel/lib/utils/elements'>;
}
declare module 'react-alice-carousel/lib/utils/index.js' {
  declare module.exports: $Exports<'react-alice-carousel/lib/utils/index'>;
}
declare module 'react-alice-carousel/lib/utils/math.js' {
  declare module.exports: $Exports<'react-alice-carousel/lib/utils/math'>;
}
declare module 'react-alice-carousel/lib/utils/style.js' {
  declare module.exports: $Exports<'react-alice-carousel/lib/utils/style'>;
}
declare module 'react-alice-carousel/lib/utils/swipe.js' {
  declare module.exports: $Exports<'react-alice-carousel/lib/utils/swipe'>;
}
declare module 'react-alice-carousel/lib/utils/timers.js' {
  declare module.exports: $Exports<'react-alice-carousel/lib/utils/timers'>;
}
declare module 'react-alice-carousel/lib/views/DotsNavigation.js' {
  declare module.exports: $Exports<'react-alice-carousel/lib/views/DotsNavigation'>;
}
declare module 'react-alice-carousel/lib/views/index.js' {
  declare module.exports: $Exports<'react-alice-carousel/lib/views/index'>;
}
declare module 'react-alice-carousel/lib/views/PlayPauseButton.js' {
  declare module.exports: $Exports<'react-alice-carousel/lib/views/PlayPauseButton'>;
}
declare module 'react-alice-carousel/lib/views/PrevNextButton.js' {
  declare module.exports: $Exports<'react-alice-carousel/lib/views/PrevNextButton'>;
}
declare module 'react-alice-carousel/lib/views/SlideInfo.js' {
  declare module.exports: $Exports<'react-alice-carousel/lib/views/SlideInfo'>;
}
declare module 'react-alice-carousel/lib/views/StageItem.js' {
  declare module.exports: $Exports<'react-alice-carousel/lib/views/StageItem'>;
}
