// flow-typed signature: dc3a332335eff84b45356f094293b1fb
// flow-typed version: <<STUB>>/synp_v^1.3.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'synp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'synp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'synp/cli/run' {
  declare module.exports: any;
}

declare module 'synp/cli/synp' {
  declare module.exports: any;
}

declare module 'synp/cli/validate-args' {
  declare module.exports: any;
}

declare module 'synp/cli/validate-path' {
  declare module.exports: any;
}

declare module 'synp/cli/write-output' {
  declare module.exports: any;
}

declare module 'synp/lib/dependencies' {
  declare module.exports: any;
}

declare module 'synp/lib/entry' {
  declare module.exports: any;
}

declare module 'synp/lib/tree' {
  declare module.exports: any;
}

declare module 'synp/test/cli.spec' {
  declare module.exports: any;
}

declare module 'synp/test/integration.spec' {
  declare module.exports: any;
}

declare module 'synp/test/mocks' {
  declare module.exports: any;
}

declare module 'synp/test/test-utils' {
  declare module.exports: any;
}

declare module 'synp/util/format' {
  declare module.exports: any;
}

declare module 'synp/util/traverse' {
  declare module.exports: any;
}

// Filename aliases
declare module 'synp/cli/run.js' {
  declare module.exports: $Exports<'synp/cli/run'>;
}
declare module 'synp/cli/synp.js' {
  declare module.exports: $Exports<'synp/cli/synp'>;
}
declare module 'synp/cli/validate-args.js' {
  declare module.exports: $Exports<'synp/cli/validate-args'>;
}
declare module 'synp/cli/validate-path.js' {
  declare module.exports: $Exports<'synp/cli/validate-path'>;
}
declare module 'synp/cli/write-output.js' {
  declare module.exports: $Exports<'synp/cli/write-output'>;
}
declare module 'synp/index' {
  declare module.exports: $Exports<'synp'>;
}
declare module 'synp/index.js' {
  declare module.exports: $Exports<'synp'>;
}
declare module 'synp/lib/dependencies.js' {
  declare module.exports: $Exports<'synp/lib/dependencies'>;
}
declare module 'synp/lib/entry.js' {
  declare module.exports: $Exports<'synp/lib/entry'>;
}
declare module 'synp/lib/tree.js' {
  declare module.exports: $Exports<'synp/lib/tree'>;
}
declare module 'synp/test/cli.spec.js' {
  declare module.exports: $Exports<'synp/test/cli.spec'>;
}
declare module 'synp/test/integration.spec.js' {
  declare module.exports: $Exports<'synp/test/integration.spec'>;
}
declare module 'synp/test/mocks.js' {
  declare module.exports: $Exports<'synp/test/mocks'>;
}
declare module 'synp/test/test-utils.js' {
  declare module.exports: $Exports<'synp/test/test-utils'>;
}
declare module 'synp/util/format.js' {
  declare module.exports: $Exports<'synp/util/format'>;
}
declare module 'synp/util/traverse.js' {
  declare module.exports: $Exports<'synp/util/traverse'>;
}
