// flow-typed signature: 1d84e7ae986b870a14c8170a183476cf
// flow-typed version: <<STUB>>/uuid-validate_v^0.0.2/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uuid-validate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uuid-validate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uuid-validate/ValidatorSpec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uuid-validate/index' {
  declare module.exports: $Exports<'uuid-validate'>;
}
declare module 'uuid-validate/index.js' {
  declare module.exports: $Exports<'uuid-validate'>;
}
declare module 'uuid-validate/ValidatorSpec.js' {
  declare module.exports: $Exports<'uuid-validate/ValidatorSpec'>;
}
