// flow-typed signature: 08109f07880d13428986e28b778e4e40
// flow-typed version: <<STUB>>/@craco/craco_v^5.0.2/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@craco/craco'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@craco/craco' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@craco/craco/bin/craco' {
  declare module.exports: any;
}

declare module '@craco/craco/bin/jest' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/args' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/config' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/cra' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/errors' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/features/babel' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/features/dev-server' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/features/eslint' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/features/plugins' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/features/style/css' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/features/style/postcss' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/features/style/sass' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/features/style/style' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/features/test/jest-babel-transform' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/features/test/jest' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/features/typescript' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/features/webpack' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/loaders' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/logger' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/paths' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/plugin-utils' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/user-config-utils' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/utils' {
  declare module.exports: any;
}

declare module '@craco/craco/scripts/build' {
  declare module.exports: any;
}

declare module '@craco/craco/scripts/start' {
  declare module.exports: any;
}

declare module '@craco/craco/scripts/test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@craco/craco/bin/craco.js' {
  declare module.exports: $Exports<'@craco/craco/bin/craco'>;
}
declare module '@craco/craco/bin/jest.js' {
  declare module.exports: $Exports<'@craco/craco/bin/jest'>;
}
declare module '@craco/craco/index' {
  declare module.exports: $Exports<'@craco/craco'>;
}
declare module '@craco/craco/index.js' {
  declare module.exports: $Exports<'@craco/craco'>;
}
declare module '@craco/craco/lib/args.js' {
  declare module.exports: $Exports<'@craco/craco/lib/args'>;
}
declare module '@craco/craco/lib/config.js' {
  declare module.exports: $Exports<'@craco/craco/lib/config'>;
}
declare module '@craco/craco/lib/cra.js' {
  declare module.exports: $Exports<'@craco/craco/lib/cra'>;
}
declare module '@craco/craco/lib/errors.js' {
  declare module.exports: $Exports<'@craco/craco/lib/errors'>;
}
declare module '@craco/craco/lib/features/babel.js' {
  declare module.exports: $Exports<'@craco/craco/lib/features/babel'>;
}
declare module '@craco/craco/lib/features/dev-server.js' {
  declare module.exports: $Exports<'@craco/craco/lib/features/dev-server'>;
}
declare module '@craco/craco/lib/features/eslint.js' {
  declare module.exports: $Exports<'@craco/craco/lib/features/eslint'>;
}
declare module '@craco/craco/lib/features/plugins.js' {
  declare module.exports: $Exports<'@craco/craco/lib/features/plugins'>;
}
declare module '@craco/craco/lib/features/style/css.js' {
  declare module.exports: $Exports<'@craco/craco/lib/features/style/css'>;
}
declare module '@craco/craco/lib/features/style/postcss.js' {
  declare module.exports: $Exports<'@craco/craco/lib/features/style/postcss'>;
}
declare module '@craco/craco/lib/features/style/sass.js' {
  declare module.exports: $Exports<'@craco/craco/lib/features/style/sass'>;
}
declare module '@craco/craco/lib/features/style/style.js' {
  declare module.exports: $Exports<'@craco/craco/lib/features/style/style'>;
}
declare module '@craco/craco/lib/features/test/jest-babel-transform.js' {
  declare module.exports: $Exports<'@craco/craco/lib/features/test/jest-babel-transform'>;
}
declare module '@craco/craco/lib/features/test/jest.js' {
  declare module.exports: $Exports<'@craco/craco/lib/features/test/jest'>;
}
declare module '@craco/craco/lib/features/typescript.js' {
  declare module.exports: $Exports<'@craco/craco/lib/features/typescript'>;
}
declare module '@craco/craco/lib/features/webpack.js' {
  declare module.exports: $Exports<'@craco/craco/lib/features/webpack'>;
}
declare module '@craco/craco/lib/loaders.js' {
  declare module.exports: $Exports<'@craco/craco/lib/loaders'>;
}
declare module '@craco/craco/lib/logger.js' {
  declare module.exports: $Exports<'@craco/craco/lib/logger'>;
}
declare module '@craco/craco/lib/paths.js' {
  declare module.exports: $Exports<'@craco/craco/lib/paths'>;
}
declare module '@craco/craco/lib/plugin-utils.js' {
  declare module.exports: $Exports<'@craco/craco/lib/plugin-utils'>;
}
declare module '@craco/craco/lib/user-config-utils.js' {
  declare module.exports: $Exports<'@craco/craco/lib/user-config-utils'>;
}
declare module '@craco/craco/lib/utils.js' {
  declare module.exports: $Exports<'@craco/craco/lib/utils'>;
}
declare module '@craco/craco/scripts/build.js' {
  declare module.exports: $Exports<'@craco/craco/scripts/build'>;
}
declare module '@craco/craco/scripts/start.js' {
  declare module.exports: $Exports<'@craco/craco/scripts/start'>;
}
declare module '@craco/craco/scripts/test.js' {
  declare module.exports: $Exports<'@craco/craco/scripts/test'>;
}
