// flow-typed signature: 6ce706a3522e1f837b46747011d8095c
// flow-typed version: <<STUB>>/@mic3/platform-ui_v^0.4.7/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mic3/platform-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mic3/platform-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mic3/platform-ui/dist/index.es' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mic3/platform-ui/dist/index.es.js' {
  declare module.exports: $Exports<'@mic3/platform-ui/dist/index.es'>;
}
